### ISSUE TITLE
codegen: generated index.ts type-checks clean but fails at runtime with ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by bug-ops** [bug-ops/mcp-execution#256]
## Description

`index.ts.hbs` re-exports each tool via a `.js`-specifier import (e.g. `'./{{typescript_name}}.js'`), while `tool.ts.hbs` imports the runtime bridge via an explicit `.ts`-specifier import (`'./_runtime/mcp-bridge.ts'`). TypeScript maps the `.js` specifier back to the sibling `.ts` file during type-checking (standard NodeNext behavior), so `tsc --noEmit` reports success on `index.ts`. Node's own module resolution does not perform this mapping: a real `.js`-specifier import that only has a `.ts` file on disk fails to resolve at runtime.

This means the `tsconfig.json` introduced for #183 (to make the generated package pass `tsc --noEmit` "out of the box") now produces a config under which `tsc` reports a clean bill of health on a package whose actual entry point (`index.ts`) cannot be loaded by Node — a regression in perceived confidence, since a consumer trusting a clean `tsc --noEmit` run has no signal that runtime resolution is broken.

## Reproduction Steps

1. Generate a package via `mcp-execution-cli generate`.
2. Run `tsc --noEmit` against the exported directory — passes cleanly.
3. Run `node --experimental-strip-types -e "import('./index.ts')"` (or equivalent type-stripping runtime invocation) from the exported directory.
4. Observe `ERR_MODULE_NOT_FOUND: Cannot find module '.../{{typescript_name}}.js' imported from .../index.ts`.

## Expected Behavior

The generated package's entry point should actually be loadable at runtime, not just type-check cleanly. Either `index.ts.hbs` should use `.ts` specifiers (consistent with `tool.ts.hbs`'s own import of the runtime bridge), or the generated files should be structured/compiled such that the emitted specifiers resolve under Node's actual module resolution.

## Actual Behavior

`index.ts` type-checks with zero errors but throws `ERR_MODULE_NOT_FOUND` when actually executed by Node, because the `.js` specifiers it re-exports through do not correspond to any file that exists on disk (only the `.ts` sibling exists).

## Environment

- Version: found alongside the #183 fix (tsconfig.json generation)
- Crate: `mcp-execution-codegen` (`crates/mcp-codegen/templates/progressive/index.ts.hbs`, `tool.ts.hbs`)

## Notes

Pre-existing gap, not introduced by #183 — but #183 makes it more consequential, since the new `tsconfig.json` now gives a false "this package works" signal via a clean `tsc --noEmit` run. Found during adversarial review of the #183 fix.
