### PR TITLE
fix(codegen): resolve runtime import specifiers and guard empty bridge content

### LINKED ISSUE #255: codegen: runtime bridge dereferences content[0] unguarded, masking real errors on empty content
## Description

`crates/mcp-codegen/templates/progressive/runtime-bridge.ts.hbs` dereferences `response.result.content[0]` without checking that `content` is non-empty, in two places:

- The `isError` handling path (around line 830): if the underlying MCP tool call fails with `isError: true` and an empty `content` array, this throws an unguarded `Cannot read properties of undefined (reading 'text')` TypeError instead of surfacing the tool's actual error — masking the real failure behind an opaque crash.
- The normal-result path (around lines 836-838): the same unguarded access applies when a successful response happens to carry empty `content`.

Additionally, MCP servers that return only `structuredContent` (supported since spec 2025-06-18) and omit `content` entirely fall into this same unguarded path — the bridge does not read `structuredContent` at all, so such responses are silently mishandled rather than surfaced as a distinct, well-typed case.

## Reproduction Steps

1. Configure or write a test MCP server that responds to a tool call with `{"isError": true, "content": []}` (empty content array on an error response), or with `{"structuredContent": {...}}` and no `content` field.
2. Call the generated tool wrapper against that server.
3. Observe an unguarded `TypeError` instead of a clear error message reflecting the tool's actual failure.

## Expected Behavior

The bridge should check that `content` is non-empty (and ideally branch on `structuredContent` when present) before indexing into it, and produce a clear, well-typed error/result instead of an opaque crash.

## Actual Behavior

`content[0]` is dereferenced unguarded in both the error and success paths; an empty (or absent, `structuredContent`-only) `content` array throws a generic property-access TypeError that hides the tool's real error or result.

## Environment

- Crate: `mcp-execution-codegen` (`crates/mcp-codegen/templates/progressive/runtime-bridge.ts.hbs`, around lines 830 and 836-838)

## Notes

Found during adversarial review of the #182 generated-`Result`-type fix. Confirmed the widened union type (`Record<string, unknown> | unknown[] | string`) itself is complete for every value `content[0]` can resolve to once dereferenced successfully — this is specifically about the unguarded dereference itself, a separate pre-existing gap from the type-shape issue #182 addressed.

### LINKED ISSUE #256: codegen: generated index.ts type-checks clean but fails at runtime with ERR_MODULE_NOT_FOUND
## Description

`index.ts.hbs` re-exports each tool via a `.js`-specifier import (e.g. `'./{{typescript_name}}.js'`), while `tool.ts.hbs` imports the runtime bridge via an explicit `.ts`-specifier import (`'./_runtime/mcp-bridge.ts'`). TypeScript maps the `.js` specifier back to the sibling `.ts` file during type-checking (standard NodeNext behavior), so `tsc --noEmit` reports success on `index.ts`. Node's own module resolution does not perform this mapping: a real `.js`-specifier import that only has a `.ts` file on disk fails to resolve at runtime.

This means the `tsconfig.json` introduced for #183 (to make the generated package pass `tsc --noEmit` "out of the box") now produces a config under which `tsc` reports a clean bill of health on a package whose actual entry point (`index.ts`) cannot be loaded by Node — a regression in perceived confidence, since a consumer trusting a clean `tsc --noEmit` run has no signal that runtime resolution is broken.

## Reproduction Steps

1. Generate a package via `mcp-execution-cli generate`.
2. Run `tsc --noEmit` against the exported directory — passes cleanly.
3. Run `node --experimental-strip-types -e "import('./index.ts')"` (or equivalent type-stripping runtime invocation) from the exported directory.
4. Observe `ERR_MODULE_NOT_FOUND: Cannot find module '.../{{typescript_name}}.js' imported from .../index.ts`.

## Expected Behavior

The generated package's entry point should actually be loadable at runtime, not just type-check cleanly. Either `index.ts.hbs` should use `.ts` specifiers (consistent with `tool.ts.hbs`'s own import of the runtime bridge), or the generated files should be structured/compiled such that the emitted specifiers resolve under Node's actual module resolution.

## Actual Behavior

`index.ts` type-checks with zero errors but throws `ERR_MODULE_NOT_FOUND` when actually executed by Node, because the `.js` specifiers it re-exports through do not correspond to any file that exists on disk (only the `.ts` sibling exists).

## Environment

- Version: found alongside the #183 fix (tsconfig.json generation)
- Crate: `mcp-execution-codegen` (`crates/mcp-codegen/templates/progressive/index.ts.hbs`, `tool.ts.hbs`)

## Notes

Pre-existing gap, not introduced by #183 — but #183 makes it more consequential, since the new `tsconfig.json` now gives a false "this package works" signal via a clean `tsc --noEmit` run. Found during adversarial review of the #183 fix.

### PR DESCRIPTION
**Pull request by bug-ops**
## Summary

- Fixes #256: `index.ts.hbs` re-exported tools and the runtime bridge via `.js` specifiers while `tool.ts.hbs` used `.ts` for the same bridge. Generated files are only ever written as `.ts`, never compiled to `.js`, so `tsc --noEmit` (which remaps `.js` back to a sibling `.ts` file for checking purposes) reported clean while Node's real ESM resolver threw `ERR_MODULE_NOT_FOUND` at runtime. All four `.js` specifiers in `index.ts.hbs` now use `.ts`, consistent with `tool.ts.hbs`.
- Fixes #255: `runtime-bridge.ts.hbs`'s `callMCPTool` dereferenced `response.result.content[0]` unguarded in both the `isError` and normal-result paths, throwing an opaque `TypeError` on empty `content` instead of surfacing the tool's actual error, and never handled `structuredContent`-only responses (spec 2025-06-18+). Both dereference sites are now guarded, with a distinct branch returning `structuredContent` when `content` is empty and `structuredContent` is present; `MCPToolCallResponse.content` is now optional and `structuredContent?: unknown` was added.
- Added 6 regression tests in `crates/mcp-codegen/tests/progressive_generation.rs`, including a real `node --experimental-strip-types` run against the full generated output (not just a `tsc` check) to catch the exact runtime-vs-typecheck divergence #256 was about.

Both issues were found during adversarial review of prior PRs (#183 and #182 respectively). Scope was held strictly to these two issues — #182's `Result` union type and #192's non-ASCII identifier handling are untouched.

## Test plan

- [x] `cargo +nightly fmt --check`
- [x] `cargo +stable clippy --all-targets --all-features --workspace -- -D warnings`
- [x] `cargo nextest run --all-features --workspace --no-fail-fast` (895/895 passed)
- [x] `cargo test --doc --all-features --workspace`
- [x] `RUSTDOCFLAGS="--deny rustdoc::broken_intra_doc_links" cargo doc --no-deps --workspace`
- [x] Reviewed by an independent adversarial critique pass (verdict: minor, no blockers) and a code-review pass (verdict: approved)

### CODE REVIEW

**Comment by bug-ops** [comment]
Note for whoever merges the unmerged \`fix/182-codegen-result-tsconfig\` branch next (adds the generated \`tsconfig.json\` with \`allowImportingTsExtensions\`): that branch also touches roughly 196 lines of \`crates/mcp-codegen/tests/progressive_generation.rs\`, the same file this PR adds ~322 lines to. Whichever of the two branches lands second will likely need a manual merge of that test file — flagged during adversarial review, not a blocker for this PR.
